name: Check
on: [push,pull_request]
jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v6
      with:
        python-version: '3.11'
    - uses: astral-sh/setup-uv@v7
      with:
        python-version: '3.11'
    - run: uv pip install --system --editable scripts/fror
    - run: uv pip install --system black mypy
    - name: Black
      run: uv run black --check --diff scripts
    - name: mypy
      run: uv run mypy --explicit-package-bases -p libfror -p fror
