name: Check
on: [push,pull_request]
jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v6
      with:
        python-version: '3.11'
        cache: 'pip'
    - run: pip install -r scripts/requirements.txt
    - name: Black
      working-directory: ./scripts
      run: python -m black --check --diff .
    - name: mypy
      working-directory: ./scripts
      run: python -m mypy --explicit-package-bases libfror fror.py
